sudo: false
language: scala
scala:
- 2.12.2
script:
- sbt clean 'release with-defaults'
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
branches:
  only:
  - master
env:
  global:
  - secure: pYSI1K/hcghf5jo6hm6ci/n0AGYFkOLrii7U4hqtY/1oKRuASF8uluFotS23ZpAUNSTOueWmpauxqIAOc7vuPZEll2H7K1Cq1Gf2mKwTS+Ko4lo9gnhd88hQ3ClwTHOJ2/cDhEd+ya8Xu+hmq18Rs83NZ3p/6W8KuX4KudAb787yjGWHrxeMLe6EJDxhwrO0E+bDmvmNUX6hZ1vYpSdB+w0LGNUX9g4bnmFAwExLW/7yYusnYNfRQnQxh3kOcWVORUidxw530ULykNCl9Lg0YHQf1erG0L8P6Ri7gZJ5SvC34Bzjm3YrQGYddpzHqTFz5MblHppC1hZEhIBUsOpkCvqkMLDFAZBrTkOV4oWWEscHaIMfSR+Y9QCF6QqFVMpqvQXMW4s6pFh81hpqHKbqzxTMH7usdWgR5MlRLhgWrzssKiePyzLsZnj+bJOfAYLP9g8en8cVB6YFID5pSKcgX/8mIdS7PmUNOARSKlzYeOO4sS8qRkSM58T4ayJynpCUc4S9q59a5DPwmk/BsJpdSFKwhPMtOEZxDrLfCtVd4u7t0ALCmLsQJ/mCSw8DiK60DvhuHoeWZYHmJNDM7O1C3jRqFvZWmlQtZzIHdjbuz48RbWIrLmGqohrg0hqQtCCGPFmi2S++nxCDtk5m9Eavchg7lwazUJ7rohskig0/KYA=
  - secure: bYx7lTYbaE1oRiwNrepi59btUe+HyqQJAmMf/46yleXNq7a8dPsAQNBj+or2S0/2y5lYKLYVxIQ/UbOv7I4JeA1DqgfLZ2uWXPg+XtkpIoWOEuhGixR0ZIqj3kysXyLWHpBw72+DSKTlq2s5FUxGmHy88Mclpxr2c3zTEWglvMsi4prkDaUzeNCMOWJ6Sfi4TmihKQ9CjwaLyMLzhlPcYEzyZvWHP+N/WxfIvUXJYbLvd7DDXLuiUvllMveeIcsZc4HFu1ff6z4Hl/2AwQetX+drbh6Evu419cksXvTUobTkb/NgPrhqPZmET/xCfLOWj9LVGIfmInol2B3jEvTWiWOBZQHt3VPAFdTwruWEg4rVs4AFyaH9xHEtJuRSVXoOTCYoL68m53tjznhiS7pWUi8PugKupKyzIVlUPhtzDfPUvYpKPA6q5UXv3hrSGmie5pRZ9NUhadqKeEQWdZOZ+0mRHxNmpD9yLugYCgc6ZQfv1/KLwHrBlfyi3neSiVS7boe9u7pwHAZgQ3HR3zH6E18PeRdjJdyWlo2Fs0vBKZ6C6/HVUGx+pBx+bZ31HbbRrWhdhkc5hviS7HOcDVCqzMkecymy83eBmMYYyw45nNz24xdVng9j+d5KHHOIi4IJzH1fAlnSQNER64udgnMVBj02O/uQJ3bXgoi2JuBCPWo=
