sudo: false
language: scala
scala:
- 2.12.2
script:
- sbt clean test publish
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
env:
  global:
  - secure: GR+aVIOirNUBaxjfa3CTMftbJBMKQlh4JRpL5BF0DZ+qSJ6BExsGTRjQ7cK30599dlCCkOpE0t1abu9w1qZuxTPBIGYJo8Hqf4vhoUepUs43OpaCRbi7jShZc4hOqcF6a1sIen5dTN+IwhuqJhI59nRoGdGFTjKa37JWLMPAn/d0mUOfqkzisJouXrS48m/BkrY+YJatKhDzwgSE/KWwEpZScE3bf+ldYBCNibasa2pAsvAjvKm/Ey4XWiRITp942e4xa0NyeBmmEKCB1JTdAlY5i/Dqtp9JiVLJrF8ajyjyqXUCBfy2b56Y2mKA7rgTbm3GfU+vM1Q0AiMOnxKjTwBQ639/MPe26+LVPz50ISTfgGLDbSAf/7PRRpjNAFCvcOAJmxg32Z/b40PRR5wH6Tr1E107oNoECzeJrhUU3QeSJHHTr7rCcsa1cYNOEzYxtubZ4q/e0DYxXrRwOBv6HDQRUevBkMRbrr9yTu8k6MFjAWFQNT7I+MNxOvMMAwJjG6Dehg+zMYJCVIhV01TlA6BCjT3zNXDsKz0fjnesNo+neiTTX7xJd6x8GZqTZrzOlASQxdy9TXqsUbyMr9FIZ39axvUtLvpddCPglHtCMZuOHJWxv+uXMfkiY7Ob6x/Gicd0gVibyk0ZGPALLMBQWOi0aPVRQeHJHUcrLLtuBD0=
  - secure: WAjyfeUsgPVD3MEv7uwzlmUMEEE1uDF0AYNQWo1gqGm82PblCCfcQQ/4VZ5Lxx5t9+WrFiJny1Jb6mP2OLzZ9Yul+/W1ko4CTWKf3fVK9yuqa9bTeC3TTZgC8jqZE553hy1twX1J7/MIIR9GMtM+rYpjnxQcvlPqnrW1kSy7n4DPz3meuRSgQaq65BK9+L+vo4wBhnYQndxx7gagwNlkJ0tgbhW+bY186ohd8hm/Bz0c7SG6duNqYZvCHmIhzWcSSDH4zpT3yh6UG4n5lnacIcvbXs7uGfjbMRj7cuYl2/IbFOUl3mJ+DR8BLvenduRP1prjCTDbryFe1fL7WJdbBmUw6oQLCFh1l2gQM6qO046wp+qtF+cW7/1gGHY6vXmt6N+5nBT0S4Pi1r7RcrJ4TM18RnyialcMSX3WTnBd9r5fJyFz0gY+VWZOeMaz2p1mFwWZwo+o5JHC4f29DwA2JUcRvDbMNQB7XYXi6VgxXep0Xh/6W4YXFPQKWcNzPWNGPa5uKCCoxc3bzmUjl9SaVux6P43M9KpkmW20Vk0hHrZ9LEm655Wh5RT1FeXWvBqSj4o81PsVzS/7XStzs+vBuxYZomhvSr0k6Kvn70qkkx1ajREfdwl3c3xIsLwiWzIOpvzYl2pIpNhTMirNiLs6sQdoUZOFbPEsjZpiFcjUT0I=
# only build releases
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/