sudo: false
language: scala
scala:
- 2.12.2
script:
- sbt clean test publish
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
env:
  global:
  - secure: F0uySSDF2JGs/AmbWdI5QgfpDQc9qJ6DPpGG+gyReYCCilyfUjIyLQeDtTT+UVOpVPCKK9Yvpnj217N+Xe86PSOf+0d+tYCTrTvYmHzxShRKwXffLz1cw0gmJQ49hPurT+u6e7SdZzWyJkikYt2c7rnEbn6KfIXMh4eB9KEUV6jQHLWAU1TLq7m9GcNpWDQAscB2fMz8FBiKsOl/m/b7t1/IMPYz/hojt2d0N9dIzb1seFz2ilS2a5y3wrTyJqeHqAMYd/HzfAMGEQ2eV+iiZI4O95CgOcP8moOs0YQggwXYIcqnaIXSW8QkzgHE0uf2kHF9+xozmH+ViasNds+LxUTToGkJ8+5FCdP4EKsZZGW9V7laqjvktSNLmdHDQEoRfNgSuvTHCDgDx4km6quKb5SkjPtvCyxgJdahEYHaAIYFsP0Ucni8d6UzEac+RCyIYKgLol1FpoofQJtBNyg6uDmSAz8rjyb1ipniU6VE/ZTaZz1M9rx1aonqvEa+CeP0TPkaBEAfHAifzKyzlzQgERObqDc+K7GK83ZVufdXxcrLUwd3GqhoGT6RfCfrCT9ycLy7DiGQ3+wKQyMS1c5ysOYo8S8bSGrbXEsLllW94fwiyuhpCOZJv51n8X4tNATE0QDXGBuZ6FJMYZX561eO2lPSIWHn8j9keLyxoZJELt0=
  - secure: UZOAY3nN69W9kIaNUoJ3BzHmO3hxq/J2r3lmbhn1TidYBfswc59M/ZYZq0j1ir58gZpCUVA5DjRBLQnsZro4C8A01Ah+Q8C2wGaGxfwtFGvXLMeB/etk/UMSkSDAckp3VJJGXUkvrKEhtVSYyB5UTCY+fs0EXgnd3q2NOVdc/w6hasP0qsw7LOGJKWVLtGUEyTvhNUPBkhCGa5M/JNDzMLx/qbSVf/DoPpBYUUxnvtZ7bMdh0rS+A4/KCxN8oFzs2t9Odj4qlsv/6yGNwnhH+6KXeXtp8KiUSAlNBP3G1Z4Yh4GV8NU5/FsB6eYx6Vs3JNZOLWgz0ufuk+ab0zvT3kccDFxTfInIB6V+hDnIB8qDFDko+Lb8o+Ygc7OaWwt49A5J2qUyjU3WvtSKwVlLzAv5GOCKhVGXTQxkLiR4/ZZhGgkag8p0d2rH0ELRuq0rlDI4B3SNx9V0RZEp8sRD3jw3N6FdyfUGiB6SFVpnxaxAyRfsMSyBuaShVqaha72cA2mDj9p+Wyxm9QYopvUZ3+Oktt0atwUPGTxQJ3Fc2e5RfU5rjlw5hFgYnxCUWGFh3h3wWaDxmCOOnsL97H032fRS1voI2SJ0KJZWNjCADEdngYPxFGSMi/NpKeZGodAFLfU9bXL7pSJV5lzPQtFiHXoBNqGAZkgCg8osNLCzg9I=
