sudo: false
language: scala
scala:
- 2.12.2
script:
- sbt clean test publish
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
env:
  global:
  - secure: j+pMn0jlmN/d+dOKuih+83+yLYN8n4/B2dWj2V3RkG5TTH2BUtZRh8iXUd4j/VjJA0LTkRvWyK7l7DtSMnRkINwYdbav7U9Na4k8nyxjPIsBucaEJi3N5f1yWatbqZ3iLBcAVuZ44BOMIlGFJkw7mwjtm1OYIZ7oImcT3UHPwihBpQKCMdRvTtYfksNxIzOr31gpQ+L2zNTwDfvDQBgOEBQWd4FOPssiZ90O5jpn7KJcOqJ3IHw4Di5/wBgmK2QnPbqVSF2ybCAZ5SUqaGLJCrFj9LM3ES/bu7OJhOqOKynr1NmjhID0DTZ0CgtIRZBu3V073wInPYXTyrOdKY/n8Gn56bJ3GqEUhioC5Bc1/bekAe/1FzimBy6kD+epPCMX9y6p9vgs4HnHXoZgb0ZFPOwfYYodILW0WaBsmp3QIuEVNKl1V4HCtQl7cpoCaQ4E5uE0CI+qw/DlS9lmvWTjeciWmIWUK+LCUr5INpvYg2cKjTbM+qjiCrfUwf6uiBN5qdkAqbB3rPR5z+7wpMvWAmNlL5BScqW+TR1mv96b1NXvfKUYRJMCQKTSPzEsIfAdnu6g47ATOAdut5hdtsqPvdq31LeZw8H9Dc65ZUuoAy4EyoBwfac5rbSNAVeiFU2xGMYklc7GjRGkgugFHgN129tRa+YKdKottIUpgDrvWwQ=
  - secure: g6nohvUabeGiRIupfY6BVnVYjzFiZ5AOSGKS43J0c2xFYsCFlDkWiAFcgnmVSRjnjGP2Cj4XbhdW+4CzIpC3IAT2ouBqRxqhN6XAu+7mdNwaHt5Ka/+aK1vfACRqH8ZtuuEKoZ2KEUAzb2myEk7cHJiUfI/+QEhk4ajI1kAUmTU6PfpqkTmT+F2WsSS0dqb1C70Jo+CIE3mzSQi5kHp9t4GMXgxy2lvUCN7k2Yr1skUVjYKf96q2ZzKmTMc7KuF8ihGiykspyYVjJzxcxw72AITxcS7/gktN1F4OtWL5zgszcsYKF3v0DbWTglrnUXujoc/yWHvFGdYMmG+Eqole7FnANmrQdX69aQXR0Z4x2KQLdONZRzu9zaDJYxFhU0Vdv3DZJcMh1yz40uqd0fllQGPm9t5Df5yrr+I/VS6eMvacZvpqpHpwxSdHfTphAtgUe85ILAvCYrZjeURsx/mT3WFnHBERiG8pQmnW5qKmmTZi9AiQGsNBwhyrR87KTEX/AoDmoCFbo4Ino0L35tbj0MZ4X/gnQUJAcIShb8ICpNUXQbCjWLeMtto2e80dX4J2n7kYcRX2xTVoWyrlkYI/MvoOLuYa4VkvxxboqZ7+UP7CMqMec5ZPWB/cJqX1pSlhk6NkDxeAecZs+ucdxNEx12Tz0dvgjEZk5Rcz7I3nT4s=
