sudo: false
language: scala
scala:
- 2.12.2
script:
- sbt clean test publish
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
env:
  global:
  - secure: ia/oDYQE8hjGIlclAwZu/E078DA/6HM/av7tloyLuP8D0AkFFUe+pQhBPZsaSG+JetxMjI3Vc7Kp7UIly+5tXV096eU2Rc2qVbuyANROSjOF3AwTZWg+4nIBhAiLnJ35ZPlFa4payhiWZNJxodibp6iKqjIA2EJnWgE7Rb8KDWRWvaZQBOtD9G8lXS7eSBIeMbiBLLp9yaPs7FqEUzcOf/ZtLwX5iQWa2pwejmz8vdfHYAFGmcjN7PYaEitzTTQ0DvlarwssO5Oo5ENtBRE7pegnvGlPBSM3sAx9AEJ3iObs+fhJ1DFCbX7eNwvoh21UfSSFrpoZ60i0vAmy843vkqnatG0EaQSyG4NJu0IDvH6iPwMc3dKyRolBxuj/85I9YPEjZssESHYEofMhPLyg2jOcdmIY/G1R8V4gruegDSp8TeCjQthMLhPr1ZWu3EnDJOzEsD3aQTlLPWimaKLfWb1WfznYl+wAx+iVRu9OP2sf5PFrqX2e13fKGozsycPVcA6d9JuaEfU4D84tVYSXGTMkjOT31LQpMulKMMHRzQlKPkwzlPdeaqkM56kmx+3Z0urT5g67Mpbydm56QpWAO+FodamcrLtyLu2nWpX1UR5tEOPnH7ReG9IHnbghQyqJeBf4/X/+bhUMepFEsMHxFMJJOcjjf5ZBt1aZZ4oeB/Y=
  - secure: PTh4fAAaM3hNSizPwOt2kVcuFmPP8JgB3Ai9yqnHhgRh2Of+iY+XoBgmP7HVob6DROm1KuwrkjLWA8/o4sXfeU/vTiuned4lFAW/1Re2XttYsnpzRxgMl93EzyHrpoi7wMq0d4TuY1Y7eszLeFSZHuPedoghxPo9rJpELMvjSdAT2Dhr1H7v1VrVGUSwBri+V+ejsoheo2FjvGR0brTVX7obOn6u0vSW0meFS9UCP8R+a94bW1ss9elhtthO4RfNKw+h2VL3wF7+oFJHBfoTtowL87Z+y/hzZjsDd1aWa9PafG4JBalW3IetZpFblz3+WeOKs5u+df4GI0dxdIhn3/d4Dh/8fkzNgr9BZqRb5Xw1MmZyci7mzJEp2PhQSG1AyxVLqswba210IhWSDJWE4Q9RyOQmczrWMQIyX/3WcR7BUSu+ciH7S6JjGPxPcJKZr1wDw4MTphRIbfWQyEMaW7Ne0V+y1IouqSD48Sl79yGprORqKJFKXf4WdiNqorMOPweRMLzr1WO2/QZNM4FxK3M5jKuo+GyAeamFde0fCp4qcIYteyQm7H3ASTWMT71Fxv14pY430+UIxlfQEN39bY2MlzP38i5QIV5m7sbx1DfFpfUF2f6l5qxfbF5Je4J755GPBz2+EiJxbNAsAcRmG1SZ/kqMJPpTZ1IEwJrJzfg=
